[workspace]
members = [
    "compiler/ast"
]

[package]
name = "x-lang"
version = "0.0.1"
authors = ["peakchen90 <1558267774@qq.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
x-lang-ast = { path = "./compiler/ast" }
serde_json = "1.0.68"
tiny-json = "0.0.1"