[package]
name = "xlang-parser"
version = "0.0.1"
authors = ["peakchen90 <1558267774@qq.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serde = "1.0.130"
serde_derive = "1.0.130"